#!/bin/bash

git pull origin master;
php symfony prg:deploy-website ../piergi.com.git/ localhost -mpiergi_production -ursyncadmin -econfig/rsync_exclude.txt --go --delete

DIR_LOG=/var/www/vhosts/piergi.com/httpdocs/
cd $DIR_LOG


php app/console cache:clear