imports:
    - { resource: '@SonataTranslationBundle/Resources/config/config.yml'}

sonata_translation:
    locales: [en, it]
    default_locale: en
    # here enable the types you need
    gedmo:
        enabled: true