imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: doctrine_extensions.yml }  
    - { resource: @FrontendBundle/Resources/config/admin.yml }  
    - { resource: @FrontendBundle/Resources/config/sonata_translation.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ FrontendBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
      default_connection: default
      connections:
        default:        
          driver:   "%database_driver%"
          host:     "%database_host%"
          port:     "%database_port%"
          charset:  UTF8
          # if using pdo_sqlite as your database driver:
          #   1. add the path in parameters.yml
          #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
          #   2. Uncomment database_path in parameters.yml.dist
          #   3. Uncomment next line:
          #     path:     "%database_path%"
    orm:
        default_entity_manager: default
        entity_managers:
          default:       
            connection: default
            auto_mapping: true
            mappings:
                FrontendBundle: ~
                translatable:
                    type: annotation
                    alias: Gedmo
                    prefix: Gedmo\Translatable\Entity
                    # make sure vendor library location is correct
                    #dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity/MappedSuperclass"
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
#    encryption: "%mailer_encryption%"
#    auth_mode:  "%mailer_auth_mode%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
#    spool:     { type: memory }


# MongoDB // added by Piergi on 20150201
#doctrine_mongodb:
#    connections:
#        default:
#            server: mongodb://localhost:27017
#            options: {}
#    default_database: test_database
#    document_managers:
#        default:
#            auto_mapping: true
#            mappings:
#                translatable:
#                    type: annotation
#                    alias: GedmoDocument
#                    prefix: Gedmo\Translatable\Document
#                    # make sure vendor library location is correct
#                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Document/MappedSuperclass" 
#                loggable:
#                    type: annotation
#                    alias: Gedmo
#                    prefix: Gedmo\Loggable\Document
#                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Document"
#                tree:
#                    type: annotation
#                    alias: Gedmo
#                    prefix: Gedmo\Tree\Document
#                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Document"  
                
sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        # Your other blocks                