<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace PRG\FrontendBundle\Document;
use Doctrine\ODM\MongoDB\DocumentRepository;
//use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;

/**
 * RegisterRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends DocumentRepository
{
 
  public function updatePosition($position)
  {
    $qb = $this->createQueryBuilder();
    $query = $qb->update()
      ->field('positions.linkedinId')->equals($position['id'])
      ->field('positions.$.isCurrent')->set($position['isCurrent'])
      ->field('positions.$.title')->set($position['title'])
      ->field('positions.$.summary')->set($position['summary'])
      //->field('positions.$.location')->set($position['location'])
      ->field('positions.$.location.name')->set($position['location']['name']) //si
      //->field('positions.$.location.locale')->set('it') //it works, but useless
      ->field('positions.$.company')->set($position['company'])  
      ->field('positions.$.startDate')->set($position['startDate']);
      if(isset($position['endDate'])) {
        //dump($position['endDate']['month'] . ' ' . $position['id']);
        $qb->field('positions.$.endDate')->set($position['endDate']);
      }
      $qb->getQuery()->execute()

    ;  
    
    //dump($query);die; 
    return $query;
  }
}
